/*
 * Arun K
 * This is Player 2's choice screen
 * and open the template in the editor.
 */
package Game;

import static Game.Board.pieceTransfer1;
import static Game.Board.pieceTransfer2;
import static Game.Board.pieceTransfer3;
import static Game.Board.pieceTransfer4;
import static Game.Board.pieceTransfer5;
import static Game.Board.pieceTransfer6;
import static Game.Board.pieceTransfer7;
import static Game.Board.pieceTransfer8;
import static Game.Board.pieceTransfer9;

/**
 *
 * @author arkir7294
 */
public class Player2 extends javax.swing.JFrame {
     //Variable Declaration 
     final int A1_P2 = 2 ;
     final int A2_P2 = 2 ;
     final int A3_P2 = 2 ;
     final int B1_P2 = 2 ;
     final int B2_P2 = 2 ;
     final int B3_P2 = 2 ;
     final int C1_P2 = 2 ;
     final int C2_P2 = 2 ;
     final int C3_P2 = 2 ;
     
     public static int A1transfer_P2 ;
     public static int A2transfer_P2 ;
     public static int A3transfer_P2 ;
     public static int B1transfer_P2 ;
     public static int B2transfer_P2 ;
     public static int B3transfer_P2 ;
     public static int C1transfer_P2 ;
     public static int C2transfer_P2 ;
     public static int C3transfer_P2 ;
//     public static boolean buttonRemoval2;
    /**
     * Creates new form Player2
     */
    public Player2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        B1_button2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        C1_button2 = new javax.swing.JButton();
        PlayerInfo2_lbl = new javax.swing.JLabel();
        C2_button2 = new javax.swing.JButton();
        B2_button2 = new javax.swing.JButton();
        C3_button2 = new javax.swing.JButton();
        B3_button2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        A1_button2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        A2_button2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        A3_button2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel5.setText("B");

        B1_button2.setText("B1");
        B1_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1_button2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel6.setText("C");

        C1_button2.setText("C1");
        C1_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1_button2ActionPerformed(evt);
            }
        });

        PlayerInfo2_lbl.setText("Player Sign: O");

        C2_button2.setText("C2");
        C2_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2_button2ActionPerformed(evt);
            }
        });

        B2_button2.setText("B2");
        B2_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2_button2ActionPerformed(evt);
            }
        });

        C3_button2.setText("C3");
        C3_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3_button2ActionPerformed(evt);
            }
        });

        B3_button2.setText("B3");
        B3_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3_button2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel1.setText("1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel2.setText("2");

        A1_button2.setText("A1");
        A1_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1_button2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel3.setText("3");

        A2_button2.setText("A2");
        A2_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2_button2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel4.setText("A");

        A3_button2.setText("A3");
        A3_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3_button2ActionPerformed(evt);
            }
        });

        jButton1.setText("Return to Board");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabel4)
                                .addGap(181, 181, 181)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(47, 47, 47))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(34, 34, 34))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(A1_button2)
                                    .addComponent(A2_button2)
                                    .addComponent(A3_button2))
                                .addGap(144, 144, 144)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(B1_button2)
                                    .addComponent(B2_button2)
                                    .addComponent(B3_button2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(C2_button2)
                                    .addComponent(C1_button2)
                                    .addComponent(C3_button2))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 449, Short.MAX_VALUE)
                                .addComponent(PlayerInfo2_lbl)))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A1_button2)
                    .addComponent(B1_button2)
                    .addComponent(C1_button2)
                    .addComponent(jLabel1))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A2_button2)
                    .addComponent(C2_button2)
                    .addComponent(B2_button2)
                    .addComponent(jLabel2))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(A3_button2)
                    .addComponent(B3_button2)
                    .addComponent(C3_button2))
                .addGap(64, 64, 64)
                .addComponent(PlayerInfo2_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1_button2ActionPerformed
        B1transfer_P2 = B1_P2;
        B1_button2.setVisible(false);
        //Switches to new jframe with drawing of board
        this.setVisible(false);
        new Board().setVisible(true);
        
        //Button removal system
//        buttonRemoval2 = true;
    }//GEN-LAST:event_B1_button2ActionPerformed

    private void C1_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1_button2ActionPerformed
        C1transfer_P2 = C1_P2;
        C1_button2.setVisible(false);
        //Switches to new jframe with drawing of board
        this.setVisible(false);
        new Board().setVisible(true);
        //Button removal system
//        buttonRemoval2 = true;
    }//GEN-LAST:event_C1_button2ActionPerformed

    private void C2_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2_button2ActionPerformed
        C2transfer_P2 = C2_P2;
        C2_button2.setVisible(false);
        //Switches to new jframe with drawing of board
        this.setVisible(false);
        new Board().setVisible(true);
        //Button removal system
//        buttonRemoval2 = true;
    }//GEN-LAST:event_C2_button2ActionPerformed

    private void B2_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2_button2ActionPerformed
        B2transfer_P2 = B2_P2;
        B2_button2.setVisible(false);
        //Switches to new jframe with drawing of board
        this.setVisible(false);
        new Board().setVisible(true);
        //Button removal system
//        buttonRemoval2 = true;
    }//GEN-LAST:event_B2_button2ActionPerformed

    private void C3_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3_button2ActionPerformed
        C3transfer_P2 = C3_P2;
        C3_button2.setVisible(false);
        //Switches to new jframe with drawing of board
        this.setVisible(false);
        new Board().setVisible(true);
        //Button removal system
//        buttonRemoval2 = true;
    }//GEN-LAST:event_C3_button2ActionPerformed

    private void B3_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3_button2ActionPerformed
        B3transfer_P2 = B3_P2;
        B3_button2.setVisible(false);
        //Switches to new jframe with drawing of board
        this.setVisible(false);
        new Board().setVisible(true);
        //Button removal system
//        buttonRemoval2 = true;
    }//GEN-LAST:event_B3_button2ActionPerformed

    private void A1_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1_button2ActionPerformed
        A1transfer_P2 = A1_P2;
        A1_button2.setVisible(false);
        //Switches to new jframe with drawing of board
        this.setVisible(false);
        new Board().setVisible(true);
        //Button removal system
//        buttonRemoval2 = true;
    }//GEN-LAST:event_A1_button2ActionPerformed

    private void A2_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2_button2ActionPerformed
        A2transfer_P2 = A2_P2;
        A2_button2.setVisible(false);
        //Switches to new jframe with drawing of board
        this.setVisible(false);
        new Board().setVisible(true);
        //Button removal system
//        buttonRemoval2 = true;
    }//GEN-LAST:event_A2_button2ActionPerformed

    private void A3_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3_button2ActionPerformed
        A3transfer_P2 = A3_P2;
        A3_button2.setVisible(false);
        //Switches to new jframe with drawing of board
        this.setVisible(false);
        new Board().setVisible(true);
        //Button removal system
//        buttonRemoval2 = true;
    }//GEN-LAST:event_A3_button2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new Board().setVisible(true);
        //Button removal system
//        buttonRemoval2 = true;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        //Check if specific square has already been played then removes button
        if(pieceTransfer1.equals("X")){
            A1_button2.setVisible(false);
        }else if(pieceTransfer1.equals("O")){
            A1_button2.setVisible(false);
        }else if(pieceTransfer1.equals("A1")){
            System.out.println("Test");
        }
        
         if(pieceTransfer2.equals("X")){
            A2_button2.setVisible(false);
        }else if(pieceTransfer2.equals("O")){
            A2_button2.setVisible(false);
        }else{
            System.out.println("Test");
        }
         
          if(pieceTransfer3.equals("X")){
            A3_button2.setVisible(false);
        }else if(pieceTransfer3.equals("O")){
            A3_button2.setVisible(false);
        }else{
            System.out.println("Test");
        }
          
           if(pieceTransfer4.equals("X")){
            B1_button2.setVisible(false);
        }else if(pieceTransfer4.equals("O")){
            B1_button2.setVisible(false);
        }else{
            System.out.println("Test");
        }
           
            if(pieceTransfer5.equals("X")){
            B2_button2.setVisible(false);
        }else if(pieceTransfer5.equals("O")){
            B2_button2.setVisible(false);
        }else{
            System.out.println("Test");
        }
            
           if(pieceTransfer6.equals("X")){
            B3_button2.setVisible(false);
        }else if(pieceTransfer6.equals("O")){
            B3_button2.setVisible(false);
        }else{
            System.out.println("Test");
        }
           
           if(pieceTransfer7.equals("X")){
            C1_button2.setVisible(false);
        }else if(pieceTransfer7.equals("O")){
            C1_button2.setVisible(false);
        }else{
            System.out.println("Test");
        }
           
           if(pieceTransfer8.equals("X")){
            C2_button2.setVisible(false);
        }else if(pieceTransfer8.equals("O")){
            C2_button2.setVisible(false);
        }else{
            System.out.println("Test");
        }
           
           if(pieceTransfer9.equals("X")){
            C3_button2.setVisible(false);
        }else if(pieceTransfer9.equals("O")){
            C3_button2.setVisible(false);
        }else{
            System.out.println("Test");
        }
    }//GEN-LAST:event_formMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Player2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Player2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Player2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Player2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Player2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1_button2;
    private javax.swing.JButton A2_button2;
    private javax.swing.JButton A3_button2;
    private javax.swing.JButton B1_button2;
    private javax.swing.JButton B2_button2;
    private javax.swing.JButton B3_button2;
    private javax.swing.JButton C1_button2;
    private javax.swing.JButton C2_button2;
    private javax.swing.JButton C3_button2;
    private javax.swing.JLabel PlayerInfo2_lbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
