package Game;


import Game.Board;
import static Game.Board.pieceTransfer1;
import static Game.Board.pieceTransfer2;
import static Game.Board.pieceTransfer3;
import static Game.Board.pieceTransfer4;
import static Game.Board.pieceTransfer5;
import static Game.Board.pieceTransfer6;
import static Game.Board.pieceTransfer7;
import static Game.Board.pieceTransfer8;
import static Game.Board.pieceTransfer9;

/*
 * Arun K
 * This is Player 1's choice screen
 * Jan 20 2020
 */

/**
 *
 * @author arkir7294
 */
public class Player1 extends javax.swing.JFrame {
     //Variable Declaration 
     final int A1 = 1 ;
     final int A2 = 1 ;
     final int A3 = 1 ;
     final int B1 = 1 ;
     final int B2 = 1 ;
     final int B3 = 1 ;
     final int C1 = 1 ;
     final int C2 = 1 ;
     final int C3 = 1 ;
     
     String validButton1;
     String validButton2;
     String validButton3;
     String validButton4;
     String validButton5;
     String validButton6;
     String validButton7;
     String validButton8;
     String validButton9;
     
     public static int A1transfer ;
     public static int A2transfer ;
     public static int A3transfer ;
     public static int B1transfer ;
     public static int B2transfer ;
     public static int B3transfer ;
     public static int C1transfer ;
     public static int C2transfer ;
     public static int C3transfer ;
//     public static void int buttonRemoval1;
     
     
    /**
     * Creates new form Player1
     */
    public Player1() {
        initComponents();
    }
    
    public void kill(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        A1_button = new javax.swing.JButton();
        A2_button = new javax.swing.JButton();
        A3_button = new javax.swing.JButton();
        B1_button = new javax.swing.JButton();
        C1_button = new javax.swing.JButton();
        C2_button = new javax.swing.JButton();
        B2_button = new javax.swing.JButton();
        C3_button = new javax.swing.JButton();
        B3_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PlayerInfo1_lbl = new javax.swing.JLabel();
        ReturnP1_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        A1_button.setText("A1");
        A1_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1_buttonActionPerformed(evt);
            }
        });

        A2_button.setText("A2");
        A2_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2_buttonActionPerformed(evt);
            }
        });

        A3_button.setText("A3");
        A3_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3_buttonActionPerformed(evt);
            }
        });

        B1_button.setText("B1");
        B1_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1_buttonActionPerformed(evt);
            }
        });

        C1_button.setText("C1");
        C1_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1_buttonActionPerformed(evt);
            }
        });

        C2_button.setText("C2");
        C2_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2_buttonActionPerformed(evt);
            }
        });

        B2_button.setText("B2");
        B2_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2_buttonActionPerformed(evt);
            }
        });

        C3_button.setText("C3");
        C3_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3_buttonActionPerformed(evt);
            }
        });

        B3_button.setText("B3");
        B3_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3_buttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel1.setText("1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel2.setText("2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel3.setText("3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel4.setText("A");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel5.setText("B");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel6.setText("C");

        PlayerInfo1_lbl.setText("Player Sign: X");

        ReturnP1_button.setText("Return to board");
        ReturnP1_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnP1_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel4)
                .addGap(181, 181, 181)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(131, 131, 131))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(A1_button)
                    .addComponent(A2_button)
                    .addComponent(A3_button))
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(B1_button)
                    .addComponent(B2_button)
                    .addComponent(B3_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(C2_button)
                            .addComponent(C1_button)
                            .addComponent(C3_button))
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PlayerInfo1_lbl)
                        .addGap(84, 84, 84))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ReturnP1_button)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A1_button)
                    .addComponent(B1_button)
                    .addComponent(C1_button)
                    .addComponent(jLabel1))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A2_button)
                    .addComponent(C2_button)
                    .addComponent(B2_button)
                    .addComponent(jLabel2))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(A3_button)
                    .addComponent(B3_button)
                    .addComponent(C3_button))
                .addGap(64, 64, 64)
                .addComponent(PlayerInfo1_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(ReturnP1_button)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A1_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1_buttonActionPerformed
        
        A1transfer = A1;
        A1_button.setVisible(false);
        
        this.setVisible(false);
        new Board().setVisible(true);   
        
        //Continue button removal
//        buttonRemoval1 = true;
//        buttonRemoval1 = 1;
        
        
    }//GEN-LAST:event_A1_buttonActionPerformed

    private void A2_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2_buttonActionPerformed
         A2transfer = A2;
         A2_button.setVisible(false);
         //Switches to new jframe with drawing of board
        this.setVisible(false);
        new Board().setVisible(true);
        //Continue button removal
//        buttonRemoval1 = true;
//        buttonRemoval1 = 1;
    }//GEN-LAST:event_A2_buttonActionPerformed

    private void A3_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3_buttonActionPerformed
         A3transfer = A3;
         A3_button.setVisible(false);
         //Switches to new jframe with drawing of board
        this.setVisible(false);
        new Board().setVisible(true);
        //Continue button removal
//        buttonRemoval1 = true;
//        buttonRemoval1 = 1;
    }//GEN-LAST:event_A3_buttonActionPerformed

    private void B1_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1_buttonActionPerformed
         B1transfer = B1;
         B1_button.setVisible(false);
         //Switches to new jframe with drawing of board
        this.setVisible(false);
        new Board().setVisible(true);
        //Continue button removal
//        buttonRemoval1 = true;
//        buttonRemoval1 = 1;
    }//GEN-LAST:event_B1_buttonActionPerformed

    private void B2_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2_buttonActionPerformed
         B2transfer = B2;
         B2_button.setVisible(false);
         //Switches to new jframe with drawing of board
        this.setVisible(false);
        new Board().setVisible(true);
        //Continue button removal
//        buttonRemoval1 = true;
//        buttonRemoval1 = 1;
    }//GEN-LAST:event_B2_buttonActionPerformed

    private void B3_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3_buttonActionPerformed
         B3transfer = B3;
         B3_button.setVisible(false);
         //Switches to new jframe with drawing of board
        this.setVisible(false);
        new Board().setVisible(true);
        //Continue button removal
//        buttonRemoval1 = true;
//        buttonRemoval1 = 1;
    }//GEN-LAST:event_B3_buttonActionPerformed

    private void C1_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1_buttonActionPerformed
         C1transfer = C1;
         C1_button.setVisible(false);
         //Switches to new jframe with drawing of board
        this.setVisible(false);
        new Board().setVisible(true);
        //Continue button removal
//        buttonRemoval1 = true;
//        buttonRemoval1 = 1;
    }//GEN-LAST:event_C1_buttonActionPerformed

    private void C2_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2_buttonActionPerformed
         C2transfer = C2;
         C2_button.setVisible(false);
         //Switches to new jframe with drawing of board
        this.setVisible(false);
        new Board().setVisible(true);
        //Continue button removal
//        buttonRemoval1 = true;
//        buttonRemoval1 = 1;
    }//GEN-LAST:event_C2_buttonActionPerformed

    private void C3_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3_buttonActionPerformed
        C3transfer = C3;
        C3_button.setVisible(false);
         //Switches to new jframe with drawing of board
        this.setVisible(false);
        new Board().setVisible(true);
        //Continue button removal
//        buttonRemoval1 = true;
//        buttonRemoval1 = 1;
    }//GEN-LAST:event_C3_buttonActionPerformed

    private void ReturnP1_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnP1_buttonActionPerformed
        //Switches to new jframe with drawing of board
        this.setVisible(false);
        new Board().setVisible(true);
    }//GEN-LAST:event_ReturnP1_buttonActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        //Check if specific square has already been played then removes button
        if(pieceTransfer1.equals("X")){
            A1_button.setVisible(false);
        }else if(pieceTransfer1.equals("O")){
            A1_button.setVisible(false);
        }else{
            System.out.println("Yay");
        }
        
         if(pieceTransfer2.equals("X")){
            A2_button.setVisible(false);
        }else if(pieceTransfer2.equals("O")){
            A2_button.setVisible(false);
        }else{
            System.out.println("Test");
        }
         
          if(pieceTransfer3.equals("X")){
            A3_button.setVisible(false);
        }else if(pieceTransfer3.equals("O")){
            A3_button.setVisible(false);
        }else{
            System.out.println("Test");
        }
          
           if(pieceTransfer4.equals("X")){
            B1_button.setVisible(false);
        }else if(pieceTransfer4.equals("O")){
            B1_button.setVisible(false);
        }else{
            System.out.println("Test");
        }
           
            if(pieceTransfer5.equals("X")){
            B2_button.setVisible(false);
        }else if(pieceTransfer5.equals("O")){
            B2_button.setVisible(false);
        }else{
            System.out.println("Test");
        }
            
           if(pieceTransfer6.equals("X")){
            B3_button.setVisible(false);
        }else if(pieceTransfer6.equals("O")){
            B3_button.setVisible(false);
        }else{
            System.out.println("Test");
        }
           
           if(pieceTransfer7.equals("X")){
            C1_button.setVisible(false);
        }else if(pieceTransfer7.equals("O")){
            C1_button.setVisible(false);
        }else{
            System.out.println("Test");
        }
           
           if(pieceTransfer8.equals("X")){
            C2_button.setVisible(false);
        }else if(pieceTransfer8.equals("O")){
            C2_button.setVisible(false);
        }else{
            System.out.println("Test");
        }
           
           if(pieceTransfer9.equals("X")){
            C3_button.setVisible(false);
        }else if(pieceTransfer9.equals("O")){
            C3_button.setVisible(false);
        }else{
            System.out.println("Test");
        }
    }//GEN-LAST:event_formMouseMoved

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Player1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Player1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Player1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Player1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Player1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1_button;
    private javax.swing.JButton A2_button;
    private javax.swing.JButton A3_button;
    private javax.swing.JButton B1_button;
    private javax.swing.JButton B2_button;
    private javax.swing.JButton B3_button;
    private javax.swing.JButton C1_button;
    private javax.swing.JButton C2_button;
    private javax.swing.JButton C3_button;
    private javax.swing.JLabel PlayerInfo1_lbl;
    private javax.swing.JButton ReturnP1_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
